# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediafile',
            fields=[
                ('hash_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, max_length=50)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('file_type', models.CharField(db_index=True, max_length=50)),
                ('mime_type_uri', models.CharField(max_length=200)),
                ('file_uri', models.CharField(max_length=400)),
                ('filesize', models.DecimalField(decimal_places=3, max_digits=19)),
                ('highlight', models.IntegerField(default=0)),
                ('sup_json', jsonfield.fields.JSONField(blank=True, default={})),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oc_mediafiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mediafile',
            unique_together=set([('uuid', 'file_type', 'highlight')]),
        ),
    ]
