# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputFieldGroup',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('profile_uuid', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(max_length=200)),
                ('sort', models.IntegerField()),
                ('visibility', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('obs_num', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crt_fieldgroups',
                'ordering': ['profile_uuid', 'sort', 'label'],
            },
        ),
    ]
