# Generated by Django 3.1.5 on 2021-01-12 12:14

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('editorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='restore_json',
            field=jsonfield.fields.JSONField(default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict}),
        ),
    ]
