# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('foaf_type', models.CharField(max_length=50)),
                ('combined_name', models.CharField(max_length=200)),
                ('given_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('mid_init', models.CharField(max_length=5)),
                ('initials', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oc_persons',
            },
        ),
    ]
