# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('field_num', models.IntegerField()),
                ('is_keycell', models.BooleanField(default=False)),
                ('ref_name', models.CharField(db_index=True, max_length=200)),
                ('ref_orig_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=50)),
                ('field_data_type', models.CharField(max_length=50)),
                ('field_value_cat', models.CharField(max_length=50)),
                ('obs_num', models.IntegerField()),
                ('label', models.CharField(db_index=True, max_length=200)),
                ('value_prefix', models.CharField(max_length=50)),
                ('unique_count', models.IntegerField()),
                ('f_uuid', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'imp_fields',
                'ordering': ['source_id', 'field_num'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='importfield',
            unique_together=set([('source_id', 'field_num')]),
        ),
    ]
