# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('row_num', models.IntegerField(db_index=True)),
                ('field_num', models.IntegerField()),
                ('rec_hash', models.CharField(db_index=True, max_length=50)),
                ('fl_uuid', models.CharField(max_length=50)),
                ('l_uuid', models.CharField(max_length=50)),
                ('cell_ok', models.BooleanField(default=None)),
                ('record', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'imp_records',
                'ordering': ['source_id', 'row_num', 'field_num'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='importcell',
            unique_together=set([('source_id', 'row_num', 'field_num')]),
        ),
    ]
