# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpTable',
            fields=[
                ('table_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, max_length=200)),
                ('field_count', models.IntegerField()),
                ('row_count', models.IntegerField()),
                ('meta_json', jsonfield.fields.JSONField(default={})),
                ('short_des', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sm_localized_json', jsonfield.fields.JSONField(blank=True, default={})),
                ('lg_localized_json', jsonfield.fields.JSONField(blank=True, default={})),
            ],
            options={
                'db_table': 'exp_tables',
            },
        ),
    ]
