# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectMapping',
            fields=[
                ('url', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('redirect', models.CharField(db_index=True, max_length=400)),
                ('http_code', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oc_redirects',
            },
        ),
    ]
