# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFieldAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('field_num', models.IntegerField()),
                ('predicate', models.CharField(db_index=True, max_length=50)),
                ('predicate_field_num', models.IntegerField()),
                ('object_field_num', models.IntegerField()),
                ('object_uuid', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'imp_field_annotations',
                'ordering': ['source_id', 'field_num'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='importfieldannotation',
            unique_together=set([('source_id', 'field_num', 'predicate', 'predicate_field_num', 'object_field_num', 'object_uuid')]),
        ),
    ]
