# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('uuid', models.CharField(db_index=True, max_length=200, null=True)),
                ('item_type', models.CharField(max_length=50, null=True)),
                ('label', models.CharField(db_index=True, max_length=200, null=True)),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('deleted_ids', models.TextField(null=True)),
                ('json_note', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reversion.Revision')),
            ],
            options={
                'db_table': 'reversion_metadata',
            },
        ),
    ]
