# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('hash_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, max_length=50)),
                ('item_type', models.CharField(db_index=True, max_length=50)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('event_id', models.IntegerField()),
                ('meta_type', models.CharField(max_length=50)),
                ('when_type', models.CharField(max_length=50)),
                ('feature_id', models.IntegerField()),
                ('earliest', models.DecimalField(decimal_places=5, max_digits=19)),
                ('start', models.DecimalField(decimal_places=5, max_digits=19)),
                ('stop', models.DecimalField(decimal_places=5, max_digits=19)),
                ('latest', models.DecimalField(decimal_places=5, max_digits=19)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'oc_events',
                'ordering': ['earliest', 'start', 'stop', 'latest'],
            },
        ),
    ]
