# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpField',
            fields=[
                ('hash_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('table_id', models.CharField(db_index=True, max_length=50)),
                ('field_num', models.IntegerField()),
                ('label', models.CharField(db_index=True, max_length=200)),
                ('rel_ids', jsonfield.fields.JSONField(db_index=True, default={})),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exp_fields',
                'ordering': ['table_id', 'field_num'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='expfield',
            unique_together=set([('table_id', 'field_num')]),
        ),
    ]
