# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trinomial',
            fields=[
                ('uri', models.CharField(db_index=True, max_length=200)),
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, max_length=200, null=True)),
                ('project_label', models.CharField(max_length=200)),
                ('trinomial', models.CharField(db_index=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=4, null=True)),
                ('county', models.CharField(max_length=4, null=True)),
                ('site', models.CharField(max_length=10, null=True)),
                ('tdar_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dinaa_trinomials',
            },
        ),
    ]
