# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geospace',
            fields=[
                ('hash_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, max_length=50)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('item_type', models.CharField(db_index=True, max_length=50)),
                ('feature_id', models.IntegerField()),
                ('meta_type', models.CharField(max_length=50)),
                ('ftype', models.CharField(db_index=True, max_length=200)),
                ('latitude', models.DecimalField(decimal_places=21, max_digits=24)),
                ('longitude', models.DecimalField(decimal_places=21, max_digits=24)),
                ('specificity', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('coordinates', models.TextField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'oc_geospace',
            },
        ),
    ]
