# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('hash_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_index=True, max_length=50)),
                ('subject_type', models.CharField(choices=[('subjects', 'subjects'), ('media', 'media'), ('documents', 'documents'), ('projects', 'projects'), ('persons', 'persons'), ('types', 'types'), ('predicates', 'predicates'), ('tables', 'tables'), ('vocabularies', 'vocabularies')], max_length=50)),
                ('project_uuid', models.CharField(max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('obs_node', models.CharField(max_length=50)),
                ('obs_num', models.IntegerField()),
                ('sort', models.DecimalField(decimal_places=3, max_digits=8)),
                ('visibility', models.IntegerField()),
                ('certainty', models.DecimalField(decimal_places=3, max_digits=4)),
                ('predicate_uuid', models.CharField(db_index=True, max_length=50)),
                ('object_uuid', models.CharField(db_index=True, max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('data_num', models.DecimalField(blank=True, decimal_places=10, max_digits=19)),
                ('data_date', models.DateTimeField(blank=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sup_json', jsonfield.fields.JSONField(blank=True, default={})),
            ],
            options={
                'db_table': 'oc_assertions',
                'ordering': ['uuid', 'sort'],
            },
        ),
    ]
