# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObsMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=200)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('obs_num', models.IntegerField()),
                ('label', models.CharField(max_length=200)),
                ('obs_type', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'oc_obsmetadata',
            },
        ),
        migrations.AlterUniqueTogether(
            name='obsmetadata',
            unique_together=set([('source_id', 'obs_num')]),
        ),
    ]
