# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputRelation',
            fields=[
                ('hash_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('profile_uuid', models.CharField(db_index=True, max_length=50)),
                ('sort', models.IntegerField()),
                ('subject_uuid', models.CharField(db_index=True, max_length=50)),
                ('subject_type', models.CharField(max_length=50)),
                ('predicate', models.CharField(db_index=True, max_length=50)),
                ('object_uuid', models.CharField(db_index=True, max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crt_relations',
                'ordering': ['profile_uuid', 'sort', 'subject_uuid', 'predicate', 'object_uuid'],
            },
        ),
    ]
