# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StableIdentifer',
            fields=[
                ('hash_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stable_id', models.CharField(db_index=True, max_length=200)),
                ('stable_type', models.CharField(max_length=50)),
                ('uuid', models.CharField(db_index=True, max_length=50)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('item_type', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'oc_identifiers',
            },
        ),
    ]
