# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpCell',
            fields=[
                ('rec_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('table_id', models.CharField(db_index=True, max_length=50)),
                ('uuid', models.CharField(db_index=True, max_length=50)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('row_num', models.IntegerField(db_index=True)),
                ('field_num', models.IntegerField()),
                ('record', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exp_records',
                'ordering': ['table_id', 'row_num', 'field_num'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='expcell',
            unique_together=set([('table_id', 'row_num', 'field_num')]),
        ),
    ]
