google_compute:
    json_key_location: "/Volumes/ryvault1/opencontext/keys/opencontext-py-gce.json"

opencontext_vm:
    vm_box: "debian/stretch64"
    oc_github_repo: "https://github.com/ekansa/open-context-py.git"
    repo_branch: "master"

    google_provider:
      project_id: "opencontext-py"
      client_email: "raymond.yee@gmail.com"
      zone: "us-central1-f"
      name: "ry-20191010b-test6509-o  c"
      image: "debian-9-stretch-v20190916"
      machine_type: "n1-standard-2"
      network: "oc-2019-06-27-vpc"
      subnetwork: "oc-subnet"
      disk_size: 100
      vm_box: gce
      ssh_username: 'raymond.yee'
      ssh_private_key_path: "~/.ssh/id_rsa"
      tags: ['staging-instance']

opencontext_predb_vm:
    oc_github_repo: "https://github.com/ekansa/open-context-py.git"
    repo_branch: "master"

    google_provider:
      project_id: "opencontext-py"
      client_email: "raymond.yee@gmail.com"
      zone: "us-central1-f"
      name: "ry-20191015a-production"
      image: "debian-9-stretch-v20190916"
      machine_type: "n1-standard-2"
      network: "oc-2019-06-27-vpc"
      subnetwork: "oc-subnet"
      disk_size: 100
      vm_box: gce
      ssh_username: 'raymond.yee'
      ssh_private_key_path: "~/.ssh/id_rsa"
      tags: ['staging-instance']


