# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkEntity',
            fields=[
                ('uri', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('label', models.CharField(db_index=True, max_length=200)),
                ('alt_label', models.CharField(db_index=True, max_length=200)),
                ('sort', models.CharField(db_index=True, max_length=60)),
                ('vocab_uri', models.CharField(max_length=200)),
                ('ent_type', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('localized_json', jsonfield.fields.JSONField(blank=True, default={})),
            ],
            options={
                'db_table': 'link_entities',
            },
        ),
    ]
