# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkAnnotation',
            fields=[
                ('hash_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sort', models.DecimalField(decimal_places=3, max_digits=8)),
                ('subject', models.CharField(db_index=True, max_length=200)),
                ('subject_type', models.CharField(max_length=50)),
                ('project_uuid', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=200)),
                ('predicate_uri', models.CharField(db_index=True, max_length=200)),
                ('object_uri', models.CharField(db_index=True, max_length=200)),
                ('obj_extra', jsonfield.fields.JSONField(blank=True, default={})),
                ('creator_uuid', models.CharField(max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'link_annotations',
                'ordering': ['subject', 'sort'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='linkannotation',
            unique_together=set([('subject', 'predicate_uri', 'object_uri')]),
        ),
    ]
