# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCstring',
            fields=[
                ('uuid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hash_id', models.CharField(max_length=50, unique=True)),
                ('project_uuid', models.CharField(db_index=True, max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('localized_json', jsonfield.fields.JSONField(blank=True, default={})),
            ],
            options={
                'db_table': 'oc_strings',
            },
        ),
    ]
